---
- name: Install Docker on CentOS 7
  hosts: linuxclient1
  become: true
  become_user: root
  
  tasks:
    - name: Install yum-utils
      yum:
        name: yum-utils
        state: present

    - name: Download Docker repository file
      get_url:
        url: "https://download.docker.com/linux/centos/docker-ce.repo"
        dest: "/etc/yum.repos.d/docker-ce.repo"
        mode: 0644

    - name: Install Docker packages
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        disable_gpg_check: yes

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes
        
    - name: Install Python
      yum:
        name:
          - python
        state: present      

    - name: Download get-pip.py
      get_url:
        url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
        dest: /tmp/get-pip.py

    - name: Install pip
      command: python /tmp/get-pip.py

    - name: Upgrade pip
      command: pip install --upgrade pip

    - name: Install docker-SDK
      pip:
        name: docker
        
    - name: Log into Docker Hub
      docker_login:
        username: micheleDevOps
        password: pizzaMargherita
      ignore_errors: yes

    - name: Pull Docker image
      docker_image:
        name: micheleDevOps/lab
        source: pull

    - name: Create Docker container
      docker_container:
        name: tomcat
        image: micheleDevOps/lab
        state: started
        tty: true
        auto_remove: true
        ports:
          - "8080:8080"
